### ISSUE TITLE
Publish connection pool

### ISSUE THREAD

**Issue by sentilo-io** [sentilo/sentilo#12]
The connection pool used in the publish/subscribe mechanism only supports two simultaneous connections with the same host. This can provoke timeouts when the server suffers an overload.

**Comment by mmasquefa** [comment]
Feature implemented in release 1.4.0.

*Maximum concurrent connections* per route has been increased to 50, following [Apache advice] (http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html).

Value is hardcoded in the code in this release :

```Java
final PoolingClientConnectionManager pccm = new PoolingClientConnectionManager();
// Increase max total connection to 400
pccm.setMaxTotal(400);
// Increase default max connection per route to 50
pccm.setDefaultMaxPerRoute(50);

````
