### ISSUE TITLE
Assure integrity and authentication in callbacks

### ISSUE THREAD

**Issue by sentilo-io** [sentilo/sentilo#13]
This will be achieved adding a header to the callbacks based in HMAC. As shared secret key between Sentilo and the receiver will be used the authentication token.

See more:
http://en.wikipedia.org/wiki/Hash-based_message_authentication_code
http://www.smartjava.org/content/protect-rest-service-using-hmac-play-20

**Comment by mmasquefa** [comment]
Feature implemented in release 1.4.0.

You will find more info on [Securing Callbacks] (http://www.sentilo.io/xwiki/bin/view/APIDocs/Security#HSecuringCallbacks) page.
