### ISSUE TITLE
New concept "Technical details" for sensors and components

### ISSUE THREAD

**Issue by sentilo-io** [sentilo/sentilo#22]
It will be good to append a new set of properties for sensors and components with the purpose of storing technical information like: *producer*, *MAC address*, *serial number*, *power type*, *connectivity*...

This info can be stored in the *additional data* properties, but it will be better to standardize it, because it's information which is useful for all kinds of sensors and  components.

**Comment by mmasquefa** [comment]
Feature implemented in release 1.4.0.

See [API doc] (http://www.sentilo.io/xwiki/bin/view/APIDocs.Service.Catalog/CreateSensors) page to learn how to use these news parameters.
