### ISSUE TITLE
Improvements in universal viewer

### ISSUE THREAD

**Issue by sentilo-io** [sentilo/sentilo#23]
Improvements and optimisation in universal viewer:
-Georeferenced search in mongoDB
-Private elements will be displayed in the map if the user is administrator
-Optimisation of data exchanged between the front-end and the server
-When returning from an element detail, the filters and map position must be maintained
-Redesign of POIs images for component types
-Tuning of POI clustering and enhancements in spiderfy
-Improvements in info-box: redesign of L&F and several new fields added

**Comment by mmasquefa** [comment]
Features implemented in release 1.4.0.
