### ISSUE TITLE
New features in the Catalog Console

### ISSUE THREAD

**Issue by sentilo-io** [sentilo/sentilo#24]
Add new information and capacities to the Catalog Console:
- Component's list: show access type and component type
- Sensor's list: show access type
- Row number in lists: save user preferences for lists using a cookie
- Add active subscriptions at application details
- Add active subscriptions at provider details
- Add component list at provider details
- Generic excel generation for exporting of lists
- Allow multiple updating of public/private attribute for components and sensors
- Allow filtering using label fields
- When returning from an element details to the list, maintain filtering and pagination

**Comment by mmasquefa** [comment]
Features implemented in release 1.4.0.
