### ISSUE TITLE
Junit alarm test fails when doing the build

### ISSUE THREAD

**Issue by esantana** [sentilo/sentilo#28]
When performing the build I've got the following error:

Results :

Failed tests:   checkFrozenAlerts(org.sentilo.agent.alert.test.repository.FrozenRepositoryImplTest): expected:<alertTest[2]> but was:<alertTest[1]>

If anyone else is reporting this error, I presume that this should be caused for some synchronization problem, because, when I switch the  order of the assertion's array the build works fine.

  @Test
  public void checkFrozenAlerts() {
    final Set<String> members = new HashSet<String>(Arrays.asList("providerTest:sensorTest:alertTest1", "providerTest:sensorTest:alertTest2"));

    when(operations.rangeByScore(any(String.class), any(Double.class), any(Double.class))).thenReturn(members);

    final List<InternalAlert> alerts = repository.checkFrozenAlerts();

    verify(operations).rangeByScore(any(String.class), any(Double.class), any(Double.class));
    Assert.assertTrue(alerts.size() == 2);
/*
    Assert.assertEquals(alerts.get(0).getId(), alertId1);
    Assert.assertEquals(alerts.get(0).getProviderId(), providerId);
    Assert.assertEquals(alerts.get(0).getSensorId(), sensorId);
    Assert.assertEquals(alerts.get(1).getId(), alertId2);
    Assert.assertEquals(alerts.get(1).getProviderId(), providerId);
    Assert.assertEquals(alerts.get(1).getSensorId(), sensorId);
*/
    Assert.assertEquals(alerts.get(1).getId(), alertId1);
    Assert.assertEquals(alerts.get(1).getProviderId(), providerId);
    Assert.assertEquals(alerts.get(1).getSensorId(), sensorId);
    Assert.assertEquals(alerts.get(0).getId(), alertId2);
    Assert.assertEquals(alerts.get(0).getProviderId(), providerId);
    Assert.assertEquals(alerts.get(0).getSensorId(), sensorId);
  }

This work for me as a contingency for now, but it is needed  take a look at it.

**Comment by mmasquefa** [comment]
Fixed in version 1.5.0
