### ISSUE TITLE
Visualization of mobile components in public map

### ISSUE THREAD

**Issue by miquelasensio** [sentilo/sentilo#3]
In current version only the static components are visualized in the public map. Should be a good feature to show their last location in the map.

**Comment by mmasquefa** [comment]
Feature implemented in release 1.4.0.

* Route viewer:
   
   It is available under the *Explore > Route viewer* on the top menu. By default, for every mobile component the route shows the 20 last locations. This number is configurable and to change its default value you must modify the property:  
  ```   
  route.max.size=20
  ```
  which is defined in the file
  ```
  sentilo-catalog-web/src/main/resources/properties/catalog-config.properties
  ```


* sentilo-agent-location-updater:
   
   This agent automatically updates component location when an observation is published with the location field filled in.
 
   See [Setup page] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup#HPlatforminstallation) to learn how to install this new agent
