### ISSUE TITLE
Sentilo Data Access Failed error

### ISSUE THREAD

**Issue by phanikumarp** [sentilo/sentilo#30]
Hi,
i am getting stacktrace following errors while installing sentilo

https://dpaste.de/NY7H    and    https://dpaste.de/95Zp

**Comment by mmasquefa** [comment]
Hi phani,

you need to configure your MongoDB server with the default settings required by Sentilo. These settings are described in the [Setup page] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup#HMongoDBsettings). 

In addition, the second link of your message is broken.
