### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by shobhitmshr002** [sentilo/sentilo#33]
Hi I've followed steps provided in your docs but getting auth error :attached snapshot.
![sentilo_err1](https://cloud.githubusercontent.com/assets/5319187/9909077/3d168854-5cb4-11e5-9726-89ee9bea09f9.png)
![sentilo_error](https://cloud.githubusercontent.com/assets/5319187/9909078/3d16e808-5cb4-11e5-8685-a64da13d8f92.png)

**Comment by mmasquefa** [comment]
Hi,

the first error shows that your connection to MongoDB are not configured correctly. If you have followed the [Setup documentation] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup#HMongoDBsettings), your mongoDB must verify:
 * It is listening on port **27017**.
 * It has a database created with name **sentilo**.
 * It has **authentication enabled**, with login credentials preconfigured as sentilo/sentilo (username:sentilo, password:sentilo)

To configure MongoDB, you only need to follow the next instructions [MongoDB access control] (http://docs.mongodb.org/v2.4/core/access-control/) 

Before to start Sentilo, verify from command line that your MongoDB server is configured correctly. For example, you could run the following command to connect to MongoDB database *sentilo*:

     mongo -port 27017 -u sentilo -p sentilo sentilo


The second error (a 401 HTTP error) is telling us that REST requests to Sentilo don't have filled in the HTTP header IDENTITY_KEY with a valid [authentication token] (http://www.sentilo.io/xwiki/bin/view/APIDocs/Security#HAuthentication). Review your requests and verify this point.

**Comment by shobhitmshr002** [comment]
Hi 

For mongodb I've made a exact setup and now verified with your,command and got positive result,i.e. was able to connect.
In second scenario I've passed the same key as they've provided but I don't know what went wrong.
I'm attaching snapshot for mongodb verification command you've provided.
![mongo_test](https://cloud.githubusercontent.com/assets/5319187/9932717/b7d24ce0-5d63-11e5-9628-343d7202046e.png)

**Comment by shobhitmshr002** [comment]
Hi 

Can someone guide me on this.Also please provide me correct auth key/token for your API.

**Comment by mmasquefa** [comment]
Hi,
tokens for Sentilo API are generated by the Catalog web application. So you must inspect your catalog webapp and look for a valid token (see the providers or applications client menu on the admin section). Every Sentilo instance will have its owns tokens.

But in your case, the problem with the token it's related to the MongoDB access problem because tokens are stored into MongoDB and if Sentilo cannot connect to MongoDB it cannot validate neither the key or the token your provide with the API request.

So the firts step should be  to solve your MongoDB access problem from the Catalog webapp. And after view your last capture, we think that **the problem is with your MongoDB version**: version 3.x is not supported by Sentilo yet.  

As you could read in the [Setup documentation] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup#H2.Platforminfrastructure), Sentilo has been tested on versions 2.2 and 2.4 of MongoDB.

Regards,

**Comment by shobhitmshr002** [comment]
Hi I just installed desired version of mongodb and then redis but now UI is working but I'm unable to see any data,also check script creates output 1101.problem is with redis ,,,,It says:

2015-09-23 12:08:01,588 [platformScheduler-6] DEBUG org.sentilo.platform.service.impl.AdminServiceImpl - alarms 0 , orders 0 , observations 0 
2015-09-23 12:08:21,922 [platformScheduler-2] DEBUG org.sentilo.platform.service.impl.SubscribeServiceImpl - Listener container isRunning? true
2015-09-23 12:08:21,922 [platformScheduler-2] DEBUG org.sentilo.platform.service.impl.SubscribeServiceImpl - Initialize subscriptions already registered in Redis
2015-09-23 12:08:21,923 [platformScheduler-2] DEBUG org.sentilo.platform.service.impl.SubscribeServiceImpl - Not found subscriptions in Redis
2015-09-23 12:08:21,924 [platformScheduler-2] DEBUG org.sentilo.platform.service.impl.SubscribeServiceImpl - Registering a mock subscription to channel /trash/dummy
2015-09-23 12:08:31,588 [platformScheduler-9] DEBUG org.sentilo.platform.service.impl.AdminServiceImpl - alarms 0 , orders 0 , observations 0 



attaching screenshot.
![sentilo_redis_err](https://cloud.githubusercontent.com/assets/5319187/10044580/c8fbccde-6219-11e5-87cc-1f44d117b4d9.png)

**Comment by shobhitmshr002** [comment]
Also can you please tell me what does it expect from redis/use of redis?
Can I directly insert those data in to redis manually?

Thanks

**Comment by shobhitmshr002** [comment]
I am stuck please provide me solution.

**Comment by mmasquefa** [comment]
Hi,
first of all, it is important to remember that github is not the recommended place to put these questions if you need a quick response. The right place is the [Sentilo google group] (https://groups.google.com/forum/#!forum/sentilo).

Secondly, we try to response as quickly as possible,  so you must be patient.

And finally, your capture doesn't show any Redis error. All traces are in debug mode and them doesn't show unusual behaviour on Sentilo, quite the opposite. 

If you get a 1101 after run the script testServerStatus, could you verify that you have load the test data as stated in the [Setup documentation] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup#HTestdataload)?

You can also try to run the following command (from the script testServerStatus):
```
curl -I  --request GET --header "IDENTITY_KEY: c956c302086a042dd0426b4e62652273e05a6ce74d0b77f8b5602e0811025066" http://127.0.0.1:8081/data/testApp_provider 
```

and post the response.
