### ISSUE TITLE
sentilo-platform-server does not work in eclipse

### ISSUE THREAD

**Issue by zobavnk** [sentilo/sentilo#34]
i am trying to build the project within eclipse for 2 weeks. i could not succeed.
what i have done is so far:
1. i have run the maven commands and imported into eclipse.
2. i have created tomcat7 runtime environment in eclipse.
3. i have added new server to that environment.
4. i have deployed the web-catalog to the server.
5. i could not start the sentilo-platform-server in tomcat.

i am using ubuntu 14.04.
- my runtime environment points the `/usr/share/tomcat7` directory.
- i shut down tomcat7 before i open eclipse and start tomcat7 in eclipse.
- i have tried to start `SentiloServer.java` but error occurred.

   By the way, there is 2 sentilo-server directories.
![snapshot01](https://cloud.githubusercontent.com/assets/5565395/10759491/3a4fad7c-7cc0-11e5-95d1-caac0e528f60.png)

I have tried to run it 2 of them separately in 4 ways.
 - Run each `SentiloServer.java` as java application gives this error:
![snapshot03](https://cloud.githubusercontent.com/assets/5565395/10759620/063e68ba-7cc1-11e5-939d-bd6558eae62b.png)

 - Run each `SentiloServer.java` on localhost which is tomcat7 gives this error:
![snapshot02](https://cloud.githubusercontent.com/assets/5565395/10759649/32bfe080-7cc1-11e5-91de-45e3402ae512.png)

Lastly, i tested the out of the box installation which building project, placing in tomcat7 server and running bin files. it works perfectly and also i have written provider and application that works with it, no problem.

i have stuck in this point. i could not find any github issue, google group question or documents about this. could you help me please?

**Comment by mmasquefa** [comment]
Hi,

the right place to put a question like this is on Google Group.

About your questions:  Sentilo is designed as a multi-module project, so it is **absolutely normal** that you see two _SentiloServer.java_ files in your workspace (these two ones are just the same file) 

Furthermore, to start the _PubSub server_  you must run _SentiloServer_ class with a set of mandatory arguments. From the log you attached, we could see the following error  "**Invalid profile [null] ... **", and _profile_ is one of these mandatory arguments. 

If you try to build Sentilo and take a look at the script 
```
sentilo-server/bin/sentilo-server
```
you will see how to run, and with which arguments, the _SentiloServer_ class.

Another option is to read the _pom.xml_ file, from  _sentilo-platform-server_ project.  Here you will find the following lines:
```xml
<program>
  <mainClass>org.sentilo.platform.server.SentiloServer</mainClass>
	<name>sentilo-server</name>
	<jvmSettings>	
		<systemProperties>
	              <systemProperty>user.timezone=UTC</systemProperty>				                
	        </systemProperties>			                
	        <extraArguments>
	             <extraArgument>-Dspring.profiles.active=${spring.profiles.active}</extraArgument>			                  
		</extraArguments>
	</jvmSettings>
</program>
```
As you could see, mandatory arguments are:
* user.timezone (recommended value _UTC_)
*  spring.profiles.active (value must  be _dev_)


Finally, for details about how to start Sentilo, see [Set up ] (http://www.sentilo.io/xwiki/bin/view/Sentilo.Community.Documentation/Setup) page.

**Comment by mmasquefa** [comment]
Close without feedback
