### ISSUE TITLE
regarding sensor.js file

### ISSUE THREAD

**Issue by Gupta-Prat** [sentilo/sentilo#39]
Hello 
I am working on sentilo project with raspberry-pi client 
So firstly to check interaction of client with sentilo so I am doing LED operation 
I want that LED blink automaticaly and will show the output will be 1 and 0 automatically so I have to implement sensor.js file so plz help me to get the code of this prototype so the 
sensor.js file below

module.exports = {

    /**
     * Retrieve data from the sensor
     * 
     * @returns {String}
     */
    readSensorValue : function() {

        // TODO: Implement this method

        // Return some random value between 0 and 255
        var sensorValue = Math.floor((Math.random() * 255));

        return sensorValue;
    }

};

Thank You

**Comment by sentilo-io** [comment]
Gupta,
please use our [user forum](https://groups.google.com/forum/#!forum/sentilo) for this question. This place on github is aimed for issues, such as bugs etc.
Thank you
