### ISSUE TITLE
Graphics with data between two dates instead of last 10.

### ISSUE THREAD

**Issue by rcuart** [sentilo/sentilo#41]
Hi,

I'm trying to add a new functionality to the sentilo-catalog web.
The component_Detail.jsp displays the information for a sensor ID with a graphic that shows the last 10
observations.
I want to modify this one or create a new one (in that case we should be able to choose which graphic we want to watch) to show the data from the observation between two dates.
¿Is it able with the current REST API?

Thanks in advance.

**Comment by sentilo-io** [comment]
Hi rcuart,

Yes, you can filter your request using the "from" and "to" parameters: http://www.sentilo.io/xwiki/bin/view/ApiDocs.Services.Data/RetrieveSensorData

Anyway, please use the forum for this matters: https://groups.google.com/forum/#!forum/sentilo

Thanks,
Sentilo team.
