### ISSUE TITLE
More reasonable display for Sensor's Bool type

### ISSUE THREAD

**Issue by dungtm007** [sentilo/sentilo#43]
At the moment the display of Sensor's Bool type on Catalog is Null and No Null. I think it's confusing and they should be shown as their values True and False. It'll make more sense

![sentilomap](https://user-images.githubusercontent.com/11995459/28992511-73b008a8-79c8-11e7-8731-de938d6da7f7.png)

![sensor](https://user-images.githubusercontent.com/11995459/28992514-76bf25e2-79c8-11e7-9eba-822cd1f7f43d.png)

**Comment by kcech** [comment]
Hello Dung, have you tried to change the measure unit of the sensor? 
If I put there for example "occupied", the value of true is "occupied" and value of false is "not occupied".
Best Regards

**Comment by dungtm007** [comment]
Hi @kcech  

Thanks a lot. I tried and it works :)

**Comment by dungtm007** [comment]
As @kcech  pointed out the solution, the original issue should be clearly addressed
