### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by diego-gv** [sentilo/sentilo#51]
Hi, 

I try to deployment a SENTILO server and I was wondering if there are any docker images to make it quick and easy.

In case it doesn't exist, is there a plan to dockerize the architecture?

Thanks,
Diego

**Comment by sentilo-io** [comment]
Hi Diego,

Currently there isn't any docker image ready to use. 
If you want to test the platform without building form the code you could do it using the virtual machine (https://sentilo.readthedocs.io/en/latest/use_a_virtual_machine.html)
The good news are that there are initiatives arround this matter and probably there will be docker images in the future, but it's not in the near roadmap(few months).

Regards,
Sentilo team.

**Comment by diego-gv** [comment]
Ok, the virtual machine is fine for me at this moment.

Thanks!
